theme: jekyll-theme-minimal
title: "DactyloLibre"
description: "Ce petit logiciel vous permetra de vous entrainer à la dactylographie gratuitement."
source: "https://github.com/spoutnik911/DactyloLibre-CsharpVersion"
