theme: jekyll-theme-cayman
markdown: "kramdown"
kramdown:
    input: "GFM"
    syntax_highlighter: rouge
    math_engine: "mathjax"
    hard_wrap: "false"
    
lang: "fr-CH"
encoding: UTF-8
title: "DactyloLibre"
